version: '3.8'

services:

  # mariadb:  
  #   build: requirements/mariadb/
  #   container_name: mariadb
  #   restart: always
  #   networks:
  #     - inception
  #   volumes:
  #     - db_data:/var/lib/mysql/
  #   env_file: .env

  nginx:
    build: requirements/nginx/
    # container_name: nginx
    # # depends_on:
    # #   - wordpress
    # ports:
    #   - "443:443"
    # restart: always
    # networks:
    #   - inception
    # volumes:
    #   - wp_data:/var/www/
    
  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wordpress
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception
  #   volumes:
  #     - wp_data:/var/www/
  #   env_file: .env


networks:
  inception:
    driver: bridge

# volumes:
#   db_data:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "/home/${USER}/data/db"
#   wp_data:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "/home/${USER}/data/wp"
