version: "3.8"

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/celys/data/wordpress
            o: bind
            type: none
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/celys/data/mariadb
            o: bind
            type: none

services:
    mariadb:
        image: mariadb
        build: 
          context: ./requirements/mariadb
          args:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_USER_PASSWORD: ${DB_USER_PASSWORD}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        environment:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_USER_PASSWORD=${DB_USER_PASSWORD}
          - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        restart: always
        container_name: mariadb
        volumes:
          - mariadb:/var/lib/mysql
        networks: 
          - inception

    nginx:
        image: nginx
        build: ./requirements/nginx
        container_name: nginx

        ports: 
          - 443:443
        restart: always
        volumes:
          - wordpress:/var/www/wordpress
        depends_on:
          - wordpress
        networks: 
          - inception

    wordpress:
        image: wordpress
        build: 
          context: ./requirements/wordpress
          args:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_USER_PASSWORD}
            DB_HOST: ${DB_HOST}
        container_name: wordpress
        restart: always
        environment:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_USER_PASSWORD}
          - DB_HOST=${DB_HOST}
        volumes:
          - wordpress:/var/www/wordpress
        depends_on:
          - mariadb
        networks: 
          - inception

networks:
    inception:
        driver: bridge